# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
    # If you develop on Mac or Windows you can remove the vendor/ directory
    #  from the bind-mount for better performance by enabling the next line:
    #- /app/vendor
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      MAILER_DSN: smtp://mailer:1025
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    labels:
      - "traefik.enable=true"
      #      - "traefik.http.services.gamers-world.loadbalancer.server.port=80"
      - "traefik.http.routers.gamers-world.rule=Host(`gamers-world.docker.localhost`)"
      - "traefik.http.routers.gamers-world.entrypoints=web"
      - "traefik.http.routers.gamers-world-secure.rule=Host(`gamers-world.docker.localhost`)"
      - "traefik.http.routers.gamers-world-secure.entrypoints=websecure"
      - "traefik.http.routers.gamers-world-secure.tls=true"
    ports:
      - "8500:80"
    networks:
      - traefik

  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
    networks:
      - pgadmin
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "80"
###< symfony/mercure-bundle ###

networks:
  traefik:
    external: true
  pgadmin:
    external: true
