# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    networks:
      - levynkeneng_apps
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gamers-world.entrypoints=web"
      - "traefik.http.services.gamers-world.loadbalancer.server.port=80"
      - "traefik.http.routers.gamers-world.rule=Host(`gamers-world.docker.localhost`)"

  mercure:
    networks:
      - levynkeneng_apps

  database:
    networks:
      - levynkeneng_apps


networks:
  levynkeneng_apps:
    external: true
  traefik:
    external: true

